# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        pretty

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"

# Setup
title:            Hyde
tagline:          "Evgenyoliver's blog"
description:      "Evgenyoliver's blog page"
url:              http://evgenyoliver.xyz
baseurl:          /

author:
  name:           'Evgeny Ananiev'
  url:            https://twitter.com/mdo

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/silversdiamond

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Evgenyoliver
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:title/


gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-crosspost-to-medium
